// ============================================================================
// KINETIQ EXERCISE DATABASE
// Standalone library — merged with program-derived exercises in collectExercises()
// ============================================================================
var EXERCISE_DB = [

  // ── CHEST ──────────────────────────────────────────────────────────────────
  {name:'Barbell Bench Press',muscle:'Chest',equipment:'Barbell'},
  {name:'Incline Barbell Bench Press',muscle:'Chest',equipment:'Barbell'},
  {name:'Decline Barbell Bench Press',muscle:'Chest',equipment:'Barbell'},
  {name:'Close-Grip Barbell Bench Press',muscle:'Chest',equipment:'Barbell'},
  {name:'Dumbbell Bench Press',muscle:'Chest',equipment:'Dumbbell'},
  {name:'Incline Dumbbell Press',muscle:'Chest',equipment:'Dumbbell'},
  {name:'Decline Dumbbell Press',muscle:'Chest',equipment:'Dumbbell'},
  {name:'Dumbbell Flye',muscle:'Chest',equipment:'Dumbbell'},
  {name:'Incline Dumbbell Flye',muscle:'Chest',equipment:'Dumbbell'},
  {name:'Dumbbell Floor Press',muscle:'Chest',equipment:'Dumbbell'},
  {name:'Cable Crossover',muscle:'Chest',equipment:'Cable'},
  {name:'Cable Chest Flye (Low to High)',muscle:'Chest',equipment:'Cable'},
  {name:'Cable Chest Flye (High to Low)',muscle:'Chest',equipment:'Cable'},
  {name:'Single-Arm Cable Press',muscle:'Chest',equipment:'Cable'},
  {name:'Machine Chest Press',muscle:'Chest',equipment:'Machine'},
  {name:'Pec Deck (Machine Flye)',muscle:'Chest',equipment:'Machine'},
  {name:'Smith Machine Bench Press',muscle:'Chest',equipment:'Machine'},
  {name:'Push-Up',muscle:'Chest',equipment:'Bodyweight'},
  {name:'Wide-Grip Push-Up',muscle:'Chest',equipment:'Bodyweight'},
  {name:'Close-Grip Push-Up',muscle:'Chest',equipment:'Bodyweight'},
  {name:'Incline Push-Up',muscle:'Chest',equipment:'Bodyweight'},
  {name:'Decline Push-Up',muscle:'Chest',equipment:'Bodyweight'},
  {name:'Archer Push-Up',muscle:'Chest',equipment:'Bodyweight'},
  {name:'Diamond Push-Up',muscle:'Chest',equipment:'Bodyweight'},
  {name:'Clap Push-Up',muscle:'Chest',equipment:'Bodyweight'},
  {name:'Chest Dip',muscle:'Chest',equipment:'Bodyweight'},
  {name:'Landmine Press',muscle:'Chest',equipment:'Barbell'},

  // ── BACK ───────────────────────────────────────────────────────────────────
  {name:'Barbell Row (Bent-Over)',muscle:'Back',equipment:'Barbell'},
  {name:'Pendlay Row',muscle:'Back',equipment:'Barbell'},
  {name:'T-Bar Row',muscle:'Back',equipment:'Barbell'},
  {name:'Barbell Deadlift',muscle:'Back',equipment:'Barbell'},
  {name:'Sumo Deadlift',muscle:'Back',equipment:'Barbell'},
  {name:'Rack Pull',muscle:'Back',equipment:'Barbell'},
  {name:'Good Morning',muscle:'Back',equipment:'Barbell'},
  {name:'Barbell Shrug',muscle:'Back',equipment:'Barbell'},
  {name:'Dumbbell Shrug',muscle:'Back',equipment:'Dumbbell'},
  {name:'Single-Arm Dumbbell Row',muscle:'Back',equipment:'Dumbbell'},
  {name:'Chest-Supported Dumbbell Row',muscle:'Back',equipment:'Dumbbell'},
  {name:'Dumbbell Shrug',muscle:'Back',equipment:'Dumbbell'},
  {name:'Seated Cable Row',muscle:'Back',equipment:'Cable'},
  {name:'Single-Arm Cable Row',muscle:'Back',equipment:'Cable'},
  {name:'Cable Straight-Arm Pulldown',muscle:'Back',equipment:'Cable'},
  {name:'Face Pull',muscle:'Back',equipment:'Cable'},
  {name:'Lat Pulldown (Wide Grip)',muscle:'Back',equipment:'Machine'},
  {name:'Lat Pulldown (Close Grip)',muscle:'Back',equipment:'Machine'},
  {name:'Lat Pulldown (Reverse Grip)',muscle:'Back',equipment:'Machine'},
  {name:'Assisted Pull-Up Machine',muscle:'Back',equipment:'Machine'},
  {name:'Machine Row',muscle:'Back',equipment:'Machine'},
  {name:'Pull-Up',muscle:'Back',equipment:'Bodyweight'},
  {name:'Wide-Grip Pull-Up',muscle:'Back',equipment:'Bodyweight'},
  {name:'Chin-Up',muscle:'Back',equipment:'Bodyweight'},
  {name:'Neutral-Grip Pull-Up',muscle:'Back',equipment:'Bodyweight'},
  {name:'Weighted Pull-Up',muscle:'Back',equipment:'Bodyweight'},
  {name:'Inverted Row',muscle:'Back',equipment:'Bodyweight'},
  {name:'Band Pull-Apart',muscle:'Back',equipment:'Band'},
  {name:'Resistance Band Row',muscle:'Back',equipment:'Band'},

  // ── LEGS ───────────────────────────────────────────────────────────────────
  {name:'Barbell Back Squat',muscle:'Legs',equipment:'Barbell'},
  {name:'Barbell Front Squat',muscle:'Legs',equipment:'Barbell'},
  {name:'Barbell Romanian Deadlift',muscle:'Legs',equipment:'Barbell'},
  {name:'Barbell Hip Thrust',muscle:'Legs',equipment:'Barbell'},
  {name:'Barbell Lunge',muscle:'Legs',equipment:'Barbell'},
  {name:'Barbell Good Morning',muscle:'Legs',equipment:'Barbell'},
  {name:'Dumbbell Romanian Deadlift',muscle:'Legs',equipment:'Dumbbell'},
  {name:'Dumbbell Hip Thrust',muscle:'Legs',equipment:'Dumbbell'},
  {name:'Dumbbell Goblet Squat',muscle:'Legs',equipment:'Dumbbell'},
  {name:'Dumbbell Reverse Lunge',muscle:'Legs',equipment:'Dumbbell'},
  {name:'Dumbbell Walking Lunge',muscle:'Legs',equipment:'Dumbbell'},
  {name:'Dumbbell Step-Up',muscle:'Legs',equipment:'Dumbbell'},
  {name:'Bulgarian Split Squat',muscle:'Legs',equipment:'Dumbbell'},
  {name:'Dumbbell Calf Raise',muscle:'Legs',equipment:'Dumbbell'},
  {name:'Single-Leg Romanian Deadlift',muscle:'Legs',equipment:'Dumbbell'},
  {name:'Kettlebell Swing',muscle:'Legs',equipment:'Kettlebell'},
  {name:'Kettlebell Goblet Squat',muscle:'Legs',equipment:'Kettlebell'},
  {name:'Leg Press',muscle:'Legs',equipment:'Machine'},
  {name:'Leg Extension',muscle:'Legs',equipment:'Machine'},
  {name:'Leg Curl (Lying)',muscle:'Legs',equipment:'Machine'},
  {name:'Leg Curl (Seated)',muscle:'Legs',equipment:'Machine'},
  {name:'Hack Squat',muscle:'Legs',equipment:'Machine'},
  {name:'Smith Machine Squat',muscle:'Legs',equipment:'Machine'},
  {name:'Standing Calf Raise Machine',muscle:'Legs',equipment:'Machine'},
  {name:'Seated Calf Raise',muscle:'Legs',equipment:'Machine'},
  {name:'Bodyweight Squat',muscle:'Legs',equipment:'Bodyweight'},
  {name:'Jump Squat',muscle:'Legs',equipment:'Bodyweight'},
  {name:'Reverse Lunge',muscle:'Legs',equipment:'Bodyweight'},
  {name:'Walking Lunge',muscle:'Legs',equipment:'Bodyweight'},
  {name:'Lateral Lunge',muscle:'Legs',equipment:'Bodyweight'},
  {name:'Curtsy Lunge',muscle:'Legs',equipment:'Bodyweight'},
  {name:'Glute Bridge',muscle:'Legs',equipment:'Bodyweight'},
  {name:'Single-Leg Glute Bridge',muscle:'Legs',equipment:'Bodyweight'},
  {name:'Nordic Hamstring Curl',muscle:'Legs',equipment:'Bodyweight'},
  {name:'Box Jump',muscle:'Legs',equipment:'Bodyweight'},
  {name:'Step-Up',muscle:'Legs',equipment:'Bodyweight'},
  {name:'Wall Sit',muscle:'Legs',equipment:'Bodyweight'},
  {name:'Calf Raise (Bodyweight)',muscle:'Legs',equipment:'Bodyweight'},
  {name:'Single-Leg Calf Raise',muscle:'Legs',equipment:'Bodyweight'},
  {name:'Pistol Squat',muscle:'Legs',equipment:'Bodyweight'},
  {name:'Cable Hip Abduction',muscle:'Legs',equipment:'Cable'},
  {name:'Cable Glute Kickback',muscle:'Legs',equipment:'Cable'},
  {name:'Hip Abduction Machine',muscle:'Legs',equipment:'Machine'},
  {name:'Hip Adduction Machine',muscle:'Legs',equipment:'Machine'},

  // ── SHOULDERS ──────────────────────────────────────────────────────────────
  {name:'Barbell Overhead Press',muscle:'Shoulders',equipment:'Barbell'},
  {name:'Barbell Push Press',muscle:'Shoulders',equipment:'Barbell'},
  {name:'Seated Barbell Overhead Press',muscle:'Shoulders',equipment:'Barbell'},
  {name:'Barbell Upright Row',muscle:'Shoulders',equipment:'Barbell'},
  {name:'Dumbbell Shoulder Press',muscle:'Shoulders',equipment:'Dumbbell'},
  {name:'Seated Dumbbell Shoulder Press',muscle:'Shoulders',equipment:'Dumbbell'},
  {name:'Arnold Press',muscle:'Shoulders',equipment:'Dumbbell'},
  {name:'Dumbbell Lateral Raise',muscle:'Shoulders',equipment:'Dumbbell'},
  {name:'Dumbbell Front Raise',muscle:'Shoulders',equipment:'Dumbbell'},
  {name:'Dumbbell Rear Delt Fly',muscle:'Shoulders',equipment:'Dumbbell'},
  {name:'Dumbbell Upright Row',muscle:'Shoulders',equipment:'Dumbbell'},
  {name:'Cable Lateral Raise',muscle:'Shoulders',equipment:'Cable'},
  {name:'Cable Front Raise',muscle:'Shoulders',equipment:'Cable'},
  {name:'Cable Rear Delt Fly',muscle:'Shoulders',equipment:'Cable'},
  {name:'Face Pull',muscle:'Shoulders',equipment:'Cable'},
  {name:'Machine Shoulder Press',muscle:'Shoulders',equipment:'Machine'},
  {name:'Rear Delt Machine',muscle:'Shoulders',equipment:'Machine'},
  {name:'Band Lateral Raise',muscle:'Shoulders',equipment:'Band'},
  {name:'Pike Push-Up',muscle:'Shoulders',equipment:'Bodyweight'},
  {name:'Handstand Push-Up',muscle:'Shoulders',equipment:'Bodyweight'},
  {name:'Prone Y-Raise',muscle:'Shoulders',equipment:'Bodyweight'},
  {name:'Prone T-Raise',muscle:'Shoulders',equipment:'Bodyweight'},
  {name:'Wall Slide',muscle:'Shoulders',equipment:'Bodyweight'},

  // ── ARMS (BICEPS) ──────────────────────────────────────────────────────────
  {name:'Barbell Bicep Curl',muscle:'Arms',equipment:'Barbell'},
  {name:'EZ-Bar Curl',muscle:'Arms',equipment:'Barbell'},
  {name:'Reverse Barbell Curl',muscle:'Arms',equipment:'Barbell'},
  {name:'Preacher Curl (Barbell)',muscle:'Arms',equipment:'Barbell'},
  {name:'Dumbbell Bicep Curl',muscle:'Arms',equipment:'Dumbbell'},
  {name:'Hammer Curl',muscle:'Arms',equipment:'Dumbbell'},
  {name:'Concentration Curl',muscle:'Arms',equipment:'Dumbbell'},
  {name:'Incline Dumbbell Curl',muscle:'Arms',equipment:'Dumbbell'},
  {name:'Preacher Curl (Dumbbell)',muscle:'Arms',equipment:'Dumbbell'},
  {name:'Zottman Curl',muscle:'Arms',equipment:'Dumbbell'},
  {name:'Cable Bicep Curl',muscle:'Arms',equipment:'Cable'},
  {name:'Cable Hammer Curl',muscle:'Arms',equipment:'Cable'},
  {name:'Cable Rope Curl',muscle:'Arms',equipment:'Cable'},
  {name:'Machine Bicep Curl',muscle:'Arms',equipment:'Machine'},
  {name:'Band Bicep Curl',muscle:'Arms',equipment:'Band'},

  // ── ARMS (TRICEPS) ─────────────────────────────────────────────────────────
  {name:'Barbell Skull Crusher',muscle:'Arms',equipment:'Barbell'},
  {name:'Close-Grip Bench Press',muscle:'Arms',equipment:'Barbell'},
  {name:'Dumbbell Skull Crusher',muscle:'Arms',equipment:'Dumbbell'},
  {name:'Dumbbell Overhead Tricep Extension',muscle:'Arms',equipment:'Dumbbell'},
  {name:'Dumbbell Tricep Kickback',muscle:'Arms',equipment:'Dumbbell'},
  {name:'Cable Tricep Pushdown (Straight Bar)',muscle:'Arms',equipment:'Cable'},
  {name:'Cable Tricep Pushdown (Rope)',muscle:'Arms',equipment:'Cable'},
  {name:'Cable Overhead Tricep Extension',muscle:'Arms',equipment:'Cable'},
  {name:'Cable Tricep Kickback',muscle:'Arms',equipment:'Cable'},
  {name:'Tricep Dip',muscle:'Arms',equipment:'Bodyweight'},
  {name:'Bench Dip',muscle:'Arms',equipment:'Bodyweight'},
  {name:'Diamond Push-Up',muscle:'Arms',equipment:'Bodyweight'},
  {name:'Machine Tricep Extension',muscle:'Arms',equipment:'Machine'},

  // ── CORE ───────────────────────────────────────────────────────────────────
  {name:'Plank',muscle:'Core',equipment:'Bodyweight'},
  {name:'Side Plank',muscle:'Core',equipment:'Bodyweight'},
  {name:'RKC Plank',muscle:'Core',equipment:'Bodyweight'},
  {name:'Plank with Shoulder Tap',muscle:'Core',equipment:'Bodyweight'},
  {name:'Crunch',muscle:'Core',equipment:'Bodyweight'},
  {name:'Reverse Crunch',muscle:'Core',equipment:'Bodyweight'},
  {name:'Bicycle Crunch',muscle:'Core',equipment:'Bodyweight'},
  {name:'Dead Bug',muscle:'Core',equipment:'Bodyweight'},
  {name:'Bird Dog',muscle:'Core',equipment:'Bodyweight'},
  {name:'Hollow Hold',muscle:'Core',equipment:'Bodyweight'},
  {name:'V-Up',muscle:'Core',equipment:'Bodyweight'},
  {name:'Leg Raise (Lying)',muscle:'Core',equipment:'Bodyweight'},
  {name:'Hanging Leg Raise',muscle:'Core',equipment:'Bodyweight'},
  {name:'Hanging Knee Raise',muscle:'Core',equipment:'Bodyweight'},
  {name:'Dragon Flag',muscle:'Core',equipment:'Bodyweight'},
  {name:'Ab Wheel Rollout',muscle:'Core',equipment:'Bodyweight'},
  {name:'Mountain Climbers',muscle:'Core',equipment:'Bodyweight'},
  {name:'Russian Twist',muscle:'Core',equipment:'Bodyweight'},
  {name:'Superman Hold',muscle:'Core',equipment:'Bodyweight'},
  {name:'Bear Crawl',muscle:'Core',equipment:'Bodyweight'},
  {name:'L-Sit',muscle:'Core',equipment:'Bodyweight'},
  {name:'Toe Touch',muscle:'Core',equipment:'Bodyweight'},
  {name:'Pallof Press',muscle:'Core',equipment:'Cable'},
  {name:'Cable Crunch',muscle:'Core',equipment:'Cable'},
  {name:'Woodchop (Cable)',muscle:'Core',equipment:'Cable'},
  {name:'Landmine Rotation',muscle:'Core',equipment:'Barbell'},
  {name:'Ab Machine Crunch',muscle:'Core',equipment:'Machine'},
  {name:'Weighted Russian Twist',muscle:'Core',equipment:'Dumbbell'},
  {name:'Weighted Crunch',muscle:'Core',equipment:'Dumbbell'},
  {name:'Copenhagen Plank',muscle:'Core',equipment:'Bodyweight'},

  // ── CARDIO ─────────────────────────────────────────────────────────────────
  {name:'Treadmill Run',muscle:'Cardio',equipment:'Machine'},
  {name:'Treadmill Walk (Incline)',muscle:'Cardio',equipment:'Machine'},
  {name:'Stationary Bike',muscle:'Cardio',equipment:'Machine'},
  {name:'Rowing Machine',muscle:'Cardio',equipment:'Machine'},
  {name:'Elliptical',muscle:'Cardio',equipment:'Machine'},
  {name:'Stair Climber',muscle:'Cardio',equipment:'Machine'},
  {name:'SkiErg',muscle:'Cardio',equipment:'Machine'},
  {name:'Assault Bike (Air Bike)',muscle:'Cardio',equipment:'Machine'},
  {name:'Jump Rope',muscle:'Cardio',equipment:'Bodyweight'},
  {name:'Burpee',muscle:'Cardio',equipment:'Bodyweight'},
  {name:'Jumping Jacks',muscle:'Cardio',equipment:'Bodyweight'},
  {name:'High Knees',muscle:'Cardio',equipment:'Bodyweight'},
  {name:'Butt Kicks',muscle:'Cardio',equipment:'Bodyweight'},
  {name:'Box Jump',muscle:'Cardio',equipment:'Bodyweight'},
  {name:'Broad Jump',muscle:'Cardio',equipment:'Bodyweight'},
  {name:'Sprint Intervals',muscle:'Cardio',equipment:'Bodyweight'},
  {name:'Battle Ropes',muscle:'Cardio',equipment:'Bodyweight'},
  {name:'Sled Push',muscle:'Cardio',equipment:'Bodyweight'},
  {name:'Farmer Carry',muscle:'Cardio',equipment:'Dumbbell'},

  // ── MOBILITY & FLEXIBILITY ─────────────────────────────────────────────────
  {name:'Hip 90/90 Stretch',muscle:'Mobility',equipment:''},
  {name:'Pigeon Pose',muscle:'Mobility',equipment:''},
  {name:'Cat-Cow',muscle:'Mobility',equipment:''},
  {name:'World\'s Greatest Stretch',muscle:'Mobility',equipment:''},
  {name:'Hip Flexor Stretch (Kneeling)',muscle:'Mobility',equipment:''},
  {name:'Hamstring Stretch (Standing)',muscle:'Mobility',equipment:''},
  {name:'Quad Stretch (Standing)',muscle:'Mobility',equipment:''},
  {name:'Calf Stretch (Wall)',muscle:'Mobility',equipment:''},
  {name:'Doorway Chest Stretch',muscle:'Mobility',equipment:''},
  {name:'Lat Stretch',muscle:'Mobility',equipment:''},
  {name:'Thoracic Extension over Foam Roller',muscle:'Mobility',equipment:'Foam Roller'},
  {name:'Foam Roll Quads',muscle:'Mobility',equipment:'Foam Roller'},
  {name:'Foam Roll Hamstrings',muscle:'Mobility',equipment:'Foam Roller'},
  {name:'Foam Roll Calves',muscle:'Mobility',equipment:'Foam Roller'},
  {name:'Foam Roll IT Band',muscle:'Mobility',equipment:'Foam Roller'},
  {name:'Foam Roll Upper Back',muscle:'Mobility',equipment:'Foam Roller'},
  {name:'Foam Roll Lats',muscle:'Mobility',equipment:'Foam Roller'},
  {name:'Inchworm',muscle:'Mobility',equipment:''},
  {name:'Scorpion Stretch',muscle:'Mobility',equipment:''},
  {name:'Thread the Needle',muscle:'Mobility',equipment:''},
  {name:'Deep Squat Hold',muscle:'Mobility',equipment:''},
  {name:'Ankle Circles',muscle:'Mobility',equipment:''},
  {name:'Wrist Circles',muscle:'Mobility',equipment:''},
  {name:'Neck Rolls',muscle:'Mobility',equipment:''},
  {name:'Hip CARs',muscle:'Mobility',equipment:''},
  {name:'Shoulder CARs',muscle:'Mobility',equipment:''},
  {name:'Thoracic Rotation',muscle:'Mobility',equipment:''}
];
