// ============================================================================
// KINETIQ EXERCISE DATABASE
// Standalone library — merged with program-derived exercises in collectExercises()
// ============================================================================
var EXERCISE_DB = [

  // ── CHEST ──────────────────────────────────────────────────────────────────
  {name:'Barbell Bench Press',muscle:'Chest',equipment:'Barbell',desc:'Lie on a flat bench, lower the bar to mid-chest, and press up until arms are locked out.'},
  {name:'Incline Barbell Bench Press',muscle:'Chest',equipment:'Barbell',desc:'Bench press on an inclined bench to emphasize the upper chest and front delts.'},
  {name:'Decline Barbell Bench Press',muscle:'Chest',equipment:'Barbell',desc:'Bench press on a declined bench to emphasize the lower chest.'},
  {name:'Close-Grip Barbell Bench Press',muscle:'Chest',equipment:'Barbell',desc:'Bench press with hands shoulder-width or closer to shift emphasis onto the triceps.'},
  {name:'Dumbbell Bench Press',muscle:'Chest',equipment:'Dumbbell',desc:'Press two dumbbells from chest level to lockout, allowing a deeper range of motion than a barbell.'},
  {name:'Incline Dumbbell Press',muscle:'Chest',equipment:'Dumbbell',desc:'Dumbbell press on an inclined bench to target the upper chest.'},
  {name:'Decline Dumbbell Press',muscle:'Chest',equipment:'Dumbbell',desc:'Dumbbell press on a declined bench to target the lower chest.'},
  {name:'Dumbbell Flye',muscle:'Chest',equipment:'Dumbbell',desc:'Lie flat and open the arms wide with a slight elbow bend, then bring the dumbbells back together over the chest.'},
  {name:'Incline Dumbbell Flye',muscle:'Chest',equipment:'Dumbbell',desc:'Dumbbell flye performed on an incline bench to emphasize the upper chest.'},
  {name:'Dumbbell Floor Press',muscle:'Chest',equipment:'Dumbbell',desc:'Bench press performed lying on the floor, limiting range of motion to protect the shoulders.'},
  {name:'Cable Crossover',muscle:'Chest',equipment:'Cable',desc:'Standing between two high pulleys, pull the handles down and across the body to squeeze the chest.'},
  {name:'Cable Chest Flye (Low to High)',muscle:'Chest',equipment:'Cable',desc:'Cable flye pulling from low pulleys upward and across the body to target the upper chest.'},
  {name:'Cable Chest Flye (High to Low)',muscle:'Chest',equipment:'Cable',desc:'Cable flye pulling from high pulleys downward and across the body to target the lower chest.'},
  {name:'Single-Arm Cable Press',muscle:'Chest',equipment:'Cable',desc:'Press one handle forward from chest height, bracing the core against the cable\'s rotational pull.'},
  {name:'Machine Chest Press',muscle:'Chest',equipment:'Machine',desc:'Seated press on a guided machine — a stable option for building chest pressing strength.'},
  {name:'Pec Deck (Machine Flye)',muscle:'Chest',equipment:'Machine',desc:'Seated machine flye that brings the arms together in front of the chest.'},
  {name:'Smith Machine Bench Press',muscle:'Chest',equipment:'Machine',desc:'Bench press using a fixed-bar-path Smith machine for added stability.'},
  {name:'Push-Up',muscle:'Chest',equipment:'Bodyweight',desc:'From a plank position, lower the chest to the floor and press back up.'},
  {name:'Wide-Grip Push-Up',muscle:'Chest',equipment:'Bodyweight',desc:'Push-up with hands set wider than shoulders to emphasize the outer chest.'},
  {name:'Close-Grip Push-Up',muscle:'Chest',equipment:'Bodyweight',desc:'Push-up with hands close together to shift emphasis onto the triceps.'},
  {name:'Incline Push-Up',muscle:'Chest',equipment:'Bodyweight',desc:'Push-up with hands elevated on a bench or box, reducing difficulty and targeting the lower chest.'},
  {name:'Decline Push-Up',muscle:'Chest',equipment:'Bodyweight',desc:'Push-up with feet elevated, increasing difficulty and targeting the upper chest.'},
  {name:'Archer Push-Up',muscle:'Chest',equipment:'Bodyweight',desc:'Wide push-up shifting most of the bodyweight to one arm at a time.'},
  {name:'Diamond Push-Up',muscle:'Chest',equipment:'Bodyweight',desc:'Push-up with hands together forming a diamond shape, emphasizing the triceps and inner chest.'},
  {name:'Clap Push-Up',muscle:'Chest',equipment:'Bodyweight',desc:'Explosive push-up where the hands leave the floor to clap before landing.'},
  {name:'Chest Dip',muscle:'Chest',equipment:'Bodyweight',desc:'On parallel bars, lean forward and lower the body to stretch the chest, then press back up.'},
  {name:'Landmine Press',muscle:'Chest',equipment:'Barbell',desc:'Press one end of a barbell anchored in a landmine attachment up and away from the shoulder.'},

  // ── BACK ───────────────────────────────────────────────────────────────────
  {name:'Barbell Row (Bent-Over)',muscle:'Back',equipment:'Barbell',desc:'Hinge forward at the hips and row the bar to the lower ribs, squeezing the shoulder blades together.'},
  {name:'Pendlay Row',muscle:'Back',equipment:'Barbell',desc:'Bent-over row where the bar rests on the floor between each explosive rep.'},
  {name:'T-Bar Row',muscle:'Back',equipment:'Barbell',desc:'Row a landmine-anchored bar with a chest-supported or bent-over stance to build back thickness.'},
  {name:'Barbell Deadlift',muscle:'Back',equipment:'Barbell',desc:'Lift the bar from the floor to hip level by driving through the legs and extending the hips.'},
  {name:'Sumo Deadlift',muscle:'Back',equipment:'Barbell',desc:'Deadlift with a wide stance and hands inside the knees, reducing range of motion and hip strain.'},
  {name:'Rack Pull',muscle:'Back',equipment:'Barbell',desc:'Partial deadlift starting from pins set at knee height, allowing heavier loads on the upper back.'},
  {name:'Good Morning',muscle:'Back',equipment:'Barbell',desc:'With the bar on the upper back, hinge forward at the hips until the torso is near parallel, then stand tall.'},
  {name:'Barbell Shrug',muscle:'Back',equipment:'Barbell',desc:'Hold the bar at arm\'s length and elevate the shoulders straight up to target the traps.'},
  {name:'Dumbbell Shrug',muscle:'Back',equipment:'Dumbbell',desc:'Shrug with a dumbbell in each hand, allowing a more natural range of motion than a barbell.'},
  {name:'Single-Arm Dumbbell Row',muscle:'Back',equipment:'Dumbbell',desc:'Supporting the body on a bench, row a dumbbell to the hip one side at a time.'},
  {name:'Chest-Supported Dumbbell Row',muscle:'Back',equipment:'Dumbbell',desc:'Row dumbbells while lying chest-down on an incline bench, removing momentum from the lower back.'},
  {name:'Seated Cable Row',muscle:'Back',equipment:'Cable',desc:'Seated on a low pulley, row the handle to the torso while keeping the chest tall.'},
  {name:'Single-Arm Cable Row',muscle:'Back',equipment:'Cable',desc:'Cable row performed one arm at a time to address side-to-side imbalances.'},
  {name:'Cable Straight-Arm Pulldown',muscle:'Back',equipment:'Cable',desc:'With arms straight, pull a high-pulley bar down toward the thighs to isolate the lats.'},
  {name:'Face Pull',muscle:'Back',equipment:'Cable',desc:'Pull a rope attachment toward the face at eye level, elbows high, to target rear delts and upper back.'},
  {name:'Lat Pulldown (Wide Grip)',muscle:'Back',equipment:'Machine',desc:'Pull a wide bar down to the upper chest to build lat width.'},
  {name:'Lat Pulldown (Close Grip)',muscle:'Back',equipment:'Machine',desc:'Lat pulldown using a close, often V-shaped handle for a more vertical pulling path.'},
  {name:'Lat Pulldown (Reverse Grip)',muscle:'Back',equipment:'Machine',desc:'Lat pulldown with palms facing you, shifting some emphasis onto the biceps and lower lats.'},
  {name:'Assisted Pull-Up Machine',muscle:'Back',equipment:'Machine',desc:'Machine that counterbalances bodyweight to build toward an unassisted pull-up.'},
  {name:'Machine Row',muscle:'Back',equipment:'Machine',desc:'Seated, chest-supported machine row that isolates the back without balance demands.'},
  {name:'Pull-Up',muscle:'Back',equipment:'Bodyweight',desc:'Hang from a bar with an overhand grip and pull the chin above the bar.'},
  {name:'Wide-Grip Pull-Up',muscle:'Back',equipment:'Bodyweight',desc:'Pull-up with a wider-than-shoulder grip to emphasize the outer lats.'},
  {name:'Chin-Up',muscle:'Back',equipment:'Bodyweight',desc:'Pull-up variation with an underhand grip, recruiting more of the biceps.'},
  {name:'Neutral-Grip Pull-Up',muscle:'Back',equipment:'Bodyweight',desc:'Pull-up with palms facing each other, easier on the shoulders than a pronated grip.'},
  {name:'Weighted Pull-Up',muscle:'Back',equipment:'Bodyweight',desc:'Pull-up performed with added weight via a dip belt or vest for progressive overload.'},
  {name:'Inverted Row',muscle:'Back',equipment:'Bodyweight',desc:'Row your own bodyweight under a bar or rings set at an angle, keeping the body straight.'},
  {name:'Band Pull-Apart',muscle:'Back',equipment:'Band',desc:'Hold a band at arm\'s length and pull it apart to shoulder level, squeezing the shoulder blades.'},
  {name:'Resistance Band Row',muscle:'Back',equipment:'Band',desc:'Anchor a band in front of you and row it to the torso, mimicking a cable row.'},

  // ── LEGS ───────────────────────────────────────────────────────────────────
  {name:'Barbell Back Squat',muscle:'Legs',equipment:'Barbell',desc:'With the bar across the upper back, squat down until thighs are at least parallel, then drive back up.'},
  {name:'Barbell Front Squat',muscle:'Legs',equipment:'Barbell',desc:'Squat with the bar racked across the front shoulders, keeping the torso more upright than a back squat.'},
  {name:'Barbell Romanian Deadlift',muscle:'Legs',equipment:'Barbell',desc:'With a slight knee bend, hinge the hips back and lower the bar along the legs to stretch the hamstrings.'},
  {name:'Barbell Hip Thrust',muscle:'Legs',equipment:'Barbell',desc:'Upper back braced on a bench, drive the hips up with a barbell across the lap to target the glutes.'},
  {name:'Barbell Lunge',muscle:'Legs',equipment:'Barbell',desc:'With the bar on the upper back, step forward into a lunge and push back to standing.'},
  {name:'Barbell Good Morning',muscle:'Legs',equipment:'Barbell',desc:'Hip-hinge movement with the bar on the upper back, targeting the hamstrings and glutes.'},
  {name:'Dumbbell Romanian Deadlift',muscle:'Legs',equipment:'Dumbbell',desc:'Romanian deadlift performed holding dumbbells at the sides instead of a barbell.'},
  {name:'Dumbbell Hip Thrust',muscle:'Legs',equipment:'Dumbbell',desc:'Hip thrust performed with a dumbbell held across the hips instead of a barbell.'},
  {name:'Dumbbell Goblet Squat',muscle:'Legs',equipment:'Dumbbell',desc:'Hold a dumbbell vertically at the chest and squat down between the knees.'},
  {name:'Dumbbell Reverse Lunge',muscle:'Legs',equipment:'Dumbbell',desc:'Step backward into a lunge while holding dumbbells at the sides, then return to standing.'},
  {name:'Dumbbell Walking Lunge',muscle:'Legs',equipment:'Dumbbell',desc:'Continuous forward lunges holding dumbbells, alternating legs with each step.'},
  {name:'Dumbbell Step-Up',muscle:'Legs',equipment:'Dumbbell',desc:'Step onto a box or bench holding dumbbells, driving through the lead leg to stand tall.'},
  {name:'Bulgarian Split Squat',muscle:'Legs',equipment:'Dumbbell',desc:'With the rear foot elevated behind you, squat down on the front leg while holding dumbbells.'},
  {name:'Dumbbell Calf Raise',muscle:'Legs',equipment:'Dumbbell',desc:'Holding dumbbells, rise onto the toes and lower back down to work the calves.'},
  {name:'Single-Leg Romanian Deadlift',muscle:'Legs',equipment:'Dumbbell',desc:'Balancing on one leg, hinge forward while the other leg extends back, holding dumbbells for load and balance training.'},
  {name:'Kettlebell Swing',muscle:'Legs',equipment:'Kettlebell',desc:'Hinge the hips explosively to swing the kettlebell from between the legs to shoulder height.'},
  {name:'Kettlebell Goblet Squat',muscle:'Legs',equipment:'Kettlebell',desc:'Goblet squat holding a kettlebell by the horns at chest level.'},
  {name:'Leg Press',muscle:'Legs',equipment:'Machine',desc:'Seated or reclined, push a weighted platform away with the feet to build quad and glute strength.'},
  {name:'Leg Extension',muscle:'Legs',equipment:'Machine',desc:'Seated machine that isolates the quads by extending the knees against resistance.'},
  {name:'Leg Curl (Lying)',muscle:'Legs',equipment:'Machine',desc:'Lying face down, curl the machine pad toward the glutes to isolate the hamstrings.'},
  {name:'Leg Curl (Seated)',muscle:'Legs',equipment:'Machine',desc:'Seated machine variation that curls the lower legs back to isolate the hamstrings.'},
  {name:'Hack Squat',muscle:'Legs',equipment:'Machine',desc:'Angled machine squat that supports the back while loading the quads heavily.'},
  {name:'Smith Machine Squat',muscle:'Legs',equipment:'Machine',desc:'Squat using a fixed-bar-path Smith machine for added stability and control.'},
  {name:'Standing Calf Raise Machine',muscle:'Legs',equipment:'Machine',desc:'Standing machine that loads the shoulders while raising onto the toes to build the calves.'},
  {name:'Seated Calf Raise',muscle:'Legs',equipment:'Machine',desc:'Seated machine calf raise that emphasizes the soleus with the knees bent.'},
  {name:'Bodyweight Squat',muscle:'Legs',equipment:'Bodyweight',desc:'Squat down until thighs are at least parallel using just bodyweight, then stand back up.'},
  {name:'Jump Squat',muscle:'Legs',equipment:'Bodyweight',desc:'Explosive squat that finishes with a jump, building power in the legs.'},
  {name:'Reverse Lunge',muscle:'Legs',equipment:'Bodyweight',desc:'Step backward into a lunge and push through the front leg to return to standing.'},
  {name:'Walking Lunge',muscle:'Legs',equipment:'Bodyweight',desc:'Continuous forward lunges alternating legs with each step, using just bodyweight.'},
  {name:'Lateral Lunge',muscle:'Legs',equipment:'Bodyweight',desc:'Step out to the side and sit back into the hip while keeping the other leg straight.'},
  {name:'Curtsy Lunge',muscle:'Legs',equipment:'Bodyweight',desc:'Step one leg diagonally behind the other into a crossing lunge to target the glutes.'},
  {name:'Glute Bridge',muscle:'Legs',equipment:'Bodyweight',desc:'Lying on the back with knees bent, drive the hips up by squeezing the glutes.'},
  {name:'Single-Leg Glute Bridge',muscle:'Legs',equipment:'Bodyweight',desc:'Glute bridge performed with one leg extended, doubling the load on the working side.'},
  {name:'Nordic Hamstring Curl',muscle:'Legs',equipment:'Bodyweight',desc:'Kneeling with ankles anchored, lower the torso forward under control using only the hamstrings.'},
  {name:'Box Jump',muscle:'Legs',equipment:'Bodyweight',desc:'Explosively jump onto a raised box or platform, landing softly with bent knees.'},
  {name:'Step-Up',muscle:'Legs',equipment:'Bodyweight',desc:'Step onto a box or bench and drive through the lead leg to stand tall.'},
  {name:'Wall Sit',muscle:'Legs',equipment:'Bodyweight',desc:'Hold a seated position against a wall with thighs parallel to the floor.'},
  {name:'Calf Raise (Bodyweight)',muscle:'Legs',equipment:'Bodyweight',desc:'Rise onto the toes and lower back down using only bodyweight to work the calves.'},
  {name:'Single-Leg Calf Raise',muscle:'Legs',equipment:'Bodyweight',desc:'Calf raise performed on one leg at a time for added difficulty.'},
  {name:'Pistol Squat',muscle:'Legs',equipment:'Bodyweight',desc:'Single-leg squat with the other leg extended forward, demanding strength, balance, and mobility.'},
  {name:'Cable Hip Abduction',muscle:'Legs',equipment:'Cable',desc:'With an ankle cuff attached to a low cable, sweep the leg outward to target the glute medius.'},
  {name:'Cable Glute Kickback',muscle:'Legs',equipment:'Cable',desc:'With an ankle cuff attached to a low cable, kick the leg back to isolate the glutes.'},
  {name:'Hip Abduction Machine',muscle:'Legs',equipment:'Machine',desc:'Seated machine that pushes the knees outward against resistance to target the outer hips and glutes.'},
  {name:'Hip Adduction Machine',muscle:'Legs',equipment:'Machine',desc:'Seated machine that squeezes the knees together against resistance to target the inner thighs.'},

  // ── SHOULDERS ──────────────────────────────────────────────────────────────
  {name:'Barbell Overhead Press',muscle:'Shoulders',equipment:'Barbell',desc:'Standing, press the bar from shoulder height straight overhead until arms are locked out.'},
  {name:'Barbell Push Press',muscle:'Shoulders',equipment:'Barbell',desc:'Overhead press aided by a slight leg drive to move heavier loads.'},
  {name:'Seated Barbell Overhead Press',muscle:'Shoulders',equipment:'Barbell',desc:'Overhead press performed seated to remove leg drive and isolate the shoulders.'},
  {name:'Barbell Upright Row',muscle:'Shoulders',equipment:'Barbell',desc:'Pull the bar straight up along the body to chest height, leading with the elbows.'},
  {name:'Dumbbell Shoulder Press',muscle:'Shoulders',equipment:'Dumbbell',desc:'Press dumbbells from shoulder height overhead until arms are locked out.'},
  {name:'Seated Dumbbell Shoulder Press',muscle:'Shoulders',equipment:'Dumbbell',desc:'Dumbbell shoulder press performed seated for added stability.'},
  {name:'Arnold Press',muscle:'Shoulders',equipment:'Dumbbell',desc:'Shoulder press that rotates the palms from facing you to facing forward as the dumbbells rise.'},
  {name:'Dumbbell Lateral Raise',muscle:'Shoulders',equipment:'Dumbbell',desc:'Raise dumbbells out to the sides to shoulder height to target the side delts.'},
  {name:'Dumbbell Front Raise',muscle:'Shoulders',equipment:'Dumbbell',desc:'Raise dumbbells straight out in front to shoulder height to target the front delts.'},
  {name:'Dumbbell Rear Delt Fly',muscle:'Shoulders',equipment:'Dumbbell',desc:'Hinged forward, raise dumbbells out to the sides to target the rear delts.'},
  {name:'Dumbbell Upright Row',muscle:'Shoulders',equipment:'Dumbbell',desc:'Pull dumbbells straight up along the body to chest height, leading with the elbows.'},
  {name:'Cable Lateral Raise',muscle:'Shoulders',equipment:'Cable',desc:'Raise a low-pulley handle out to the side, keeping constant tension on the side delt.'},
  {name:'Cable Front Raise',muscle:'Shoulders',equipment:'Cable',desc:'Raise a low-pulley handle straight out in front to target the front delts.'},
  {name:'Cable Rear Delt Fly',muscle:'Shoulders',equipment:'Cable',desc:'Standing at a cable crossover, pull the handles out and back to target the rear delts.'},
  {name:'Face Pull',muscle:'Shoulders',equipment:'Cable',desc:'Pull a rope attachment toward the face at eye level, elbows high, to target rear delts and upper back.'},
  {name:'Machine Shoulder Press',muscle:'Shoulders',equipment:'Machine',desc:'Seated press on a guided machine — a stable option for building shoulder pressing strength.'},
  {name:'Rear Delt Machine',muscle:'Shoulders',equipment:'Machine',desc:'Seated machine flye performed facing the pad to isolate the rear delts.'},
  {name:'Band Lateral Raise',muscle:'Shoulders',equipment:'Band',desc:'Standing on a band, raise the arms out to the sides against band resistance.'},
  {name:'Pike Push-Up',muscle:'Shoulders',equipment:'Bodyweight',desc:'From a downward-dog-like position, lower the head toward the floor and press back up to target the shoulders.'},
  {name:'Handstand Push-Up',muscle:'Shoulders',equipment:'Bodyweight',desc:'Against a wall in a handstand, lower the head toward the floor and press back up.'},
  {name:'Prone Y-Raise',muscle:'Shoulders',equipment:'Bodyweight',desc:'Lying face down, raise the arms overhead in a Y shape to target the lower traps and rear delts.'},
  {name:'Prone T-Raise',muscle:'Shoulders',equipment:'Bodyweight',desc:'Lying face down, raise the arms out to the sides in a T shape to target the rear delts.'},
  {name:'Wall Slide',muscle:'Shoulders',equipment:'Bodyweight',desc:'Back against a wall, slide the arms overhead while keeping contact to improve shoulder mobility.'},

  // ── ARMS (BICEPS) ──────────────────────────────────────────────────────────
  {name:'Barbell Bicep Curl',muscle:'Arms',equipment:'Barbell',desc:'Curl the bar from thighs to shoulders, keeping the elbows pinned to the sides.'},
  {name:'EZ-Bar Curl',muscle:'Arms',equipment:'Barbell',desc:'Bicep curl using an angled EZ-bar to reduce wrist strain.'},
  {name:'Reverse Barbell Curl',muscle:'Arms',equipment:'Barbell',desc:'Curl the bar with an overhand grip to emphasize the forearms and brachialis.'},
  {name:'Preacher Curl (Barbell)',muscle:'Arms',equipment:'Barbell',desc:'Curl a bar with the upper arms braced on an angled pad to eliminate swinging.'},
  {name:'Dumbbell Bicep Curl',muscle:'Arms',equipment:'Dumbbell',desc:'Curl dumbbells from thighs to shoulders, one arm at a time or together.'},
  {name:'Hammer Curl',muscle:'Arms',equipment:'Dumbbell',desc:'Curl dumbbells with a neutral, palms-facing-in grip to target the brachialis and forearms.'},
  {name:'Concentration Curl',muscle:'Arms',equipment:'Dumbbell',desc:'Seated, brace the elbow against the inner thigh and curl the dumbbell for a strict, isolated contraction.'},
  {name:'Incline Dumbbell Curl',muscle:'Arms',equipment:'Dumbbell',desc:'Curl dumbbells while seated on an incline bench, stretching the biceps at the bottom of each rep.'},
  {name:'Preacher Curl (Dumbbell)',muscle:'Arms',equipment:'Dumbbell',desc:'Preacher curl performed with a single dumbbell for a more isolated, one-arm focus.'},
  {name:'Zottman Curl',muscle:'Arms',equipment:'Dumbbell',desc:'Curl up with palms facing forward, then rotate palms down to lower slowly, hitting both biceps and forearms.'},
  {name:'Cable Bicep Curl',muscle:'Arms',equipment:'Cable',desc:'Curl a low-pulley handle or bar, keeping constant tension on the biceps throughout the range.'},
  {name:'Cable Hammer Curl',muscle:'Arms',equipment:'Cable',desc:'Cable curl using a rope attachment with a neutral grip to target the brachialis.'},
  {name:'Cable Rope Curl',muscle:'Arms',equipment:'Cable',desc:'Curl a rope attachment, spreading the ends apart at the top for a strong peak contraction.'},
  {name:'Machine Bicep Curl',muscle:'Arms',equipment:'Machine',desc:'Seated machine curl that isolates the biceps with a guided, stable motion.'},
  {name:'Band Bicep Curl',muscle:'Arms',equipment:'Band',desc:'Stand on a band and curl the handles up, keeping the elbows fixed at the sides.'},

  // ── ARMS (TRICEPS) ─────────────────────────────────────────────────────────
  {name:'Barbell Skull Crusher',muscle:'Arms',equipment:'Barbell',desc:'Lying on a bench, lower the bar toward the forehead by bending only the elbows, then extend back up.'},
  {name:'Close-Grip Bench Press',muscle:'Arms',equipment:'Barbell',desc:'Bench press with hands shoulder-width or closer to shift emphasis onto the triceps.'},
  {name:'Dumbbell Skull Crusher',muscle:'Arms',equipment:'Dumbbell',desc:'Skull crusher performed with dumbbells for a slightly more natural wrist path.'},
  {name:'Dumbbell Overhead Tricep Extension',muscle:'Arms',equipment:'Dumbbell',desc:'Holding a dumbbell overhead with both hands, lower it behind the head and extend back up.'},
  {name:'Dumbbell Tricep Kickback',muscle:'Arms',equipment:'Dumbbell',desc:'Hinged forward with the upper arm parallel to the floor, extend the forearm back to straighten the elbow.'},
  {name:'Cable Tricep Pushdown (Straight Bar)',muscle:'Arms',equipment:'Cable',desc:'Push a high-pulley bar down by extending the elbows, keeping them pinned to the sides.'},
  {name:'Cable Tricep Pushdown (Rope)',muscle:'Arms',equipment:'Cable',desc:'Tricep pushdown using a rope attachment, spreading the ends apart at the bottom.'},
  {name:'Cable Overhead Tricep Extension',muscle:'Arms',equipment:'Cable',desc:'Facing away from a low pulley, extend the arms overhead to work the long head of the triceps.'},
  {name:'Cable Tricep Kickback',muscle:'Arms',equipment:'Cable',desc:'Tricep kickback performed against cable resistance for constant tension.'},
  {name:'Tricep Dip',muscle:'Arms',equipment:'Bodyweight',desc:'On parallel bars, lower the body with elbows close to the sides, then press back up.'},
  {name:'Bench Dip',muscle:'Arms',equipment:'Bodyweight',desc:'Hands on a bench behind you, lower the hips toward the floor and press back up.'},
  {name:'Diamond Push-Up',muscle:'Arms',equipment:'Bodyweight',desc:'Push-up with hands together forming a diamond shape, emphasizing the triceps and inner chest.'},
  {name:'Machine Tricep Extension',muscle:'Arms',equipment:'Machine',desc:'Seated machine that isolates the triceps with a guided extension motion.'},

  // ── CORE ───────────────────────────────────────────────────────────────────
  {name:'Plank',muscle:'Core',equipment:'Bodyweight',desc:'Hold a straight-body position on forearms and toes, bracing the core to prevent sagging.'},
  {name:'Side Plank',muscle:'Core',equipment:'Bodyweight',desc:'Balance on one forearm and the side of the foot, keeping the hips lifted to target the obliques.'},
  {name:'RKC Plank',muscle:'Core',equipment:'Bodyweight',desc:'High-intensity plank variation that maximally contracts glutes, abs, and lats for short, hard holds.'},
  {name:'Plank with Shoulder Tap',muscle:'Core',equipment:'Bodyweight',desc:'From a high plank, tap the opposite shoulder with each hand while resisting hip rotation.'},
  {name:'Crunch',muscle:'Core',equipment:'Bodyweight',desc:'Lying on the back with knees bent, curl the shoulders off the floor to contract the abs.'},
  {name:'Reverse Crunch',muscle:'Core',equipment:'Bodyweight',desc:'Lying on the back, curl the hips off the floor by drawing the knees toward the chest.'},
  {name:'Bicycle Crunch',muscle:'Core',equipment:'Bodyweight',desc:'Alternate bringing elbow to opposite knee in a pedaling motion to target the obliques.'},
  {name:'Dead Bug',muscle:'Core',equipment:'Bodyweight',desc:'Lying on the back, extend opposite arm and leg while keeping the low back pressed to the floor.'},
  {name:'Bird Dog',muscle:'Core',equipment:'Bodyweight',desc:'On hands and knees, extend opposite arm and leg while keeping the spine neutral.'},
  {name:'Hollow Hold',muscle:'Core',equipment:'Bodyweight',desc:'Lying on the back, lift shoulders and legs off the floor into a dish shape and hold.'},
  {name:'V-Up',muscle:'Core',equipment:'Bodyweight',desc:'Lying flat, simultaneously lift the legs and torso to touch fingers to toes.'},
  {name:'Leg Raise (Lying)',muscle:'Core',equipment:'Bodyweight',desc:'Lying on the back, raise straight legs to vertical and lower under control.'},
  {name:'Hanging Leg Raise',muscle:'Core',equipment:'Bodyweight',desc:'Hanging from a bar, raise straight legs to hip height or higher.'},
  {name:'Hanging Knee Raise',muscle:'Core',equipment:'Bodyweight',desc:'Hanging from a bar, raise bent knees toward the chest.'},
  {name:'Dragon Flag',muscle:'Core',equipment:'Bodyweight',desc:'Advanced move where the body is lowered from a bench, straight as a board, pivoting at the shoulders.'},
  {name:'Ab Wheel Rollout',muscle:'Core',equipment:'Bodyweight',desc:'Kneeling, roll a wheel forward while keeping the core braced, then pull back to start.'},
  {name:'Mountain Climbers',muscle:'Core',equipment:'Bodyweight',desc:'From a plank, drive the knees toward the chest alternately at a running pace.'},
  {name:'Russian Twist',muscle:'Core',equipment:'Bodyweight',desc:'Seated with feet lifted, rotate the torso side to side to target the obliques.'},
  {name:'Superman Hold',muscle:'Core',equipment:'Bodyweight',desc:'Lying face down, lift arms and legs off the floor simultaneously to target the lower back.'},
  {name:'Bear Crawl',muscle:'Core',equipment:'Bodyweight',desc:'Crawl forward on hands and feet with knees hovering just above the floor.'},
  {name:'L-Sit',muscle:'Core',equipment:'Bodyweight',desc:'Supported on hands, hold the legs straight out in front, parallel to the floor.'},
  {name:'Toe Touch',muscle:'Core',equipment:'Bodyweight',desc:'Lying on the back with legs raised, crunch up to reach for the toes.'},
  {name:'Pallof Press',muscle:'Core',equipment:'Cable',desc:'Standing side-on to a cable, press the handle straight out and resist the pull rotating the torso.'},
  {name:'Cable Crunch',muscle:'Core',equipment:'Cable',desc:'Kneeling under a high pulley, crunch the torso down toward the floor against cable resistance.'},
  {name:'Woodchop (Cable)',muscle:'Core',equipment:'Cable',desc:'Pull a cable diagonally across the body, from high to low or low to high, rotating through the torso.'},
  {name:'Landmine Rotation',muscle:'Core',equipment:'Barbell',desc:'Holding one end of a landmine-anchored bar, rotate it side to side using the core.'},
  {name:'Ab Machine Crunch',muscle:'Core',equipment:'Machine',desc:'Seated machine crunch that loads the abs through a guided range of motion.'},
  {name:'Weighted Russian Twist',muscle:'Core',equipment:'Dumbbell',desc:'Russian twist performed holding a dumbbell or plate for added resistance.'},
  {name:'Weighted Crunch',muscle:'Core',equipment:'Dumbbell',desc:'Crunch performed holding a weight at the chest for added resistance.'},
  {name:'Copenhagen Plank',muscle:'Core',equipment:'Bodyweight',desc:'Side plank with the top leg supported on a bench, heavily targeting the inner thigh and obliques.'},

  // ── CARDIO ─────────────────────────────────────────────────────────────────
  {name:'Treadmill Run',muscle:'Cardio',equipment:'Machine',desc:'Steady or interval running on a treadmill to build cardiovascular endurance.'},
  {name:'Treadmill Walk (Incline)',muscle:'Cardio',equipment:'Machine',desc:'Walking on an inclined treadmill for low-impact cardio and leg conditioning.'},
  {name:'Stationary Bike',muscle:'Cardio',equipment:'Machine',desc:'Low-impact cycling for steady-state or interval cardio work.'},
  {name:'Rowing Machine',muscle:'Cardio',equipment:'Machine',desc:'Full-body cardio pulling motion that also builds back and leg endurance.'},
  {name:'Elliptical',muscle:'Cardio',equipment:'Machine',desc:'Low-impact machine combining a striding and pushing motion for cardio conditioning.'},
  {name:'Stair Climber',muscle:'Cardio',equipment:'Machine',desc:'Continuous stepping machine that builds cardio and lower body endurance.'},
  {name:'SkiErg',muscle:'Cardio',equipment:'Machine',desc:'Standing pulling machine that mimics a skiing motion for full-body cardio.'},
  {name:'Assault Bike (Air Bike)',muscle:'Cardio',equipment:'Machine',desc:'Fan-resistance bike using both arms and legs, popular for high-intensity intervals.'},
  {name:'Jump Rope',muscle:'Cardio',equipment:'Bodyweight',desc:'Continuous rope skipping for cardio conditioning and coordination.'},
  {name:'Burpee',muscle:'Cardio',equipment:'Bodyweight',desc:'Drop into a push-up, then explode up into a jump — a full-body conditioning move.'},
  {name:'Jumping Jacks',muscle:'Cardio',equipment:'Bodyweight',desc:'Jump the feet out while raising the arms overhead, then return to start.'},
  {name:'High Knees',muscle:'Cardio',equipment:'Bodyweight',desc:'Run in place driving the knees up toward the chest at a fast pace.'},
  {name:'Butt Kicks',muscle:'Cardio',equipment:'Bodyweight',desc:'Run in place kicking the heels back toward the glutes at a fast pace.'},
  {name:'Box Jump',muscle:'Cardio',equipment:'Bodyweight',desc:'Explosively jump onto a raised box or platform, landing softly with bent knees.'},
  {name:'Broad Jump',muscle:'Cardio',equipment:'Bodyweight',desc:'Jump forward for maximum horizontal distance, landing softly with bent knees.'},
  {name:'Sprint Intervals',muscle:'Cardio',equipment:'Bodyweight',desc:'Short bursts of maximum-effort running followed by rest or easy jogging.'},
  {name:'Battle Ropes',muscle:'Cardio',equipment:'Bodyweight',desc:'Alternate slamming heavy ropes up and down for high-intensity upper body conditioning.'},
  {name:'Sled Push',muscle:'Cardio',equipment:'Bodyweight',desc:'Drive a weighted sled forward across the floor using the legs.'},
  {name:'Farmer Carry',muscle:'Cardio',equipment:'Dumbbell',desc:'Walk for distance or time while carrying a heavy dumbbell or kettlebell in each hand.'},

  // ── MOBILITY & FLEXIBILITY ─────────────────────────────────────────────────
  {name:'Hip 90/90 Stretch',muscle:'Mobility',equipment:'',desc:'Seated with both legs bent at 90 degrees, rotate through the hips to improve internal and external rotation.'},
  {name:'Pigeon Pose',muscle:'Mobility',equipment:'',desc:'One leg bent in front, one extended behind, lean forward to stretch the hip of the front leg.'},
  {name:'Cat-Cow',muscle:'Mobility',equipment:'',desc:'On hands and knees, alternate arching and rounding the spine to mobilize the back.'},
  {name:'World\'s Greatest Stretch',muscle:'Mobility',equipment:'',desc:'Multi-part lunge stretch that moves through hip, hamstring, and thoracic mobility in one flow.'},
  {name:'Hip Flexor Stretch (Kneeling)',muscle:'Mobility',equipment:'',desc:'Kneeling lunge position that stretches the hip flexor of the rear leg.'},
  {name:'Hamstring Stretch (Standing)',muscle:'Mobility',equipment:'',desc:'Standing forward fold or leg-up variation to stretch the back of the legs.'},
  {name:'Quad Stretch (Standing)',muscle:'Mobility',equipment:'',desc:'Standing, pull one heel toward the glutes to stretch the front of the thigh.'},
  {name:'Calf Stretch (Wall)',muscle:'Mobility',equipment:'',desc:'Lean into a wall with one leg extended behind you to stretch the calf.'},
  {name:'Doorway Chest Stretch',muscle:'Mobility',equipment:'',desc:'Arm braced against a doorway, lean forward to stretch across the chest and front shoulder.'},
  {name:'Lat Stretch',muscle:'Mobility',equipment:'',desc:'Reach overhead and lean to the side, or hang from a bar, to stretch the lats.'},
  {name:'Thoracic Extension over Foam Roller',muscle:'Mobility',equipment:'Foam Roller',desc:'Lying over a foam roller placed under the upper back, extend backward to open up the thoracic spine.'},
  {name:'Foam Roll Quads',muscle:'Mobility',equipment:'Foam Roller',desc:'Roll the front of the thighs over a foam roller to release tension.'},
  {name:'Foam Roll Hamstrings',muscle:'Mobility',equipment:'Foam Roller',desc:'Roll the back of the thighs over a foam roller to release tension.'},
  {name:'Foam Roll Calves',muscle:'Mobility',equipment:'Foam Roller',desc:'Roll the calves over a foam roller to release tension.'},
  {name:'Foam Roll IT Band',muscle:'Mobility',equipment:'Foam Roller',desc:'Roll the outside of the thigh over a foam roller to release the IT band.'},
  {name:'Foam Roll Upper Back',muscle:'Mobility',equipment:'Foam Roller',desc:'Roll the upper back over a foam roller to release tension between the shoulder blades.'},
  {name:'Foam Roll Lats',muscle:'Mobility',equipment:'Foam Roller',desc:'Roll the side of the torso over a foam roller to release the lats.'},
  {name:'Inchworm',muscle:'Mobility',equipment:'',desc:'From standing, walk the hands out to a plank and back to the feet, stretching the hamstrings and warming up the whole body.'},
  {name:'Scorpion Stretch',muscle:'Mobility',equipment:'',desc:'Lying face down, rotate one leg across the body toward the opposite hand to stretch the hip and low back.'},
  {name:'Thread the Needle',muscle:'Mobility',equipment:'',desc:'On hands and knees, thread one arm under the body to rotate and stretch the upper back.'},
  {name:'Deep Squat Hold',muscle:'Mobility',equipment:'',desc:'Hold the bottom of a bodyweight squat to open up the hips and ankles.'},
  {name:'Ankle Circles',muscle:'Mobility',equipment:'',desc:'Rotate the ankle through its full range of motion to warm up the joint.'},
  {name:'Wrist Circles',muscle:'Mobility',equipment:'',desc:'Rotate the wrist through its full range of motion to warm up the joint.'},
  {name:'Neck Rolls',muscle:'Mobility',equipment:'',desc:'Gently rotate the neck through its range of motion to release tension.'},
  {name:'Hip CARs',muscle:'Mobility',equipment:'',desc:'Controlled Articular Rotations — slow, deliberate circles through the hip\'s full range of motion.'},
  {name:'Shoulder CARs',muscle:'Mobility',equipment:'',desc:'Controlled Articular Rotations — slow, deliberate circles through the shoulder\'s full range of motion.'},
  {name:'Thoracic Rotation',muscle:'Mobility',equipment:'',desc:'On hands and knees or seated, rotate through the upper back to improve thoracic mobility.'}
];
